name: "FlexCI"

on:
  push:
    branches: ["main", "v[0-9]+", "hotfix-*"]
  issue_comment:
    types: [created]

permissions:
  contents: read
  statuses: write

jobs:
  dispatch:
    if: |
        github.repository_owner == 'cupy' &&
        (
            (github.event_name == 'issue_comment' &&
             github.event.issue.pull_request &&
             contains(github.event.comment.body, '/test ')) ||
            (github.event_name == 'push')
        )
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Setup Environment
      run: |
        pip install pygithub

    - name: Dispatch
      env:
        GITHUB_TOKEN: ${{ github.token }}
        FLEXCI_WEBHOOK_SECRET: ${{ secrets.FLEXCI_WEBHOOK_SECRET }}
      run: |
        ./.github/workflows/scripts/flexci_dispatcher.py \
            --event "${GITHUB_EVENT_NAME}" \
            --webhook "${GITHUB_EVENT_PATH}" \
            --projects ./.pfnci/config.tags.json \
            --external-tag jenkins
