name: "Publish to PyPI"
run-name: "Publish to PyPI (${{ inputs.release }} - ${{ inputs.branch }})"

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Source: cupy-release-tools"
        type: choice
        options:
          - main
          - v12
      release:
        description: "Release to Publish (draft/tag, e.g., v13.0.0a1)"
        default: "v13.0.0rc9"

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: cupy/cupy-release-tools
        ref: ${{ inputs.branch }}
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Check
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pip install distlib
        echo '```' >> "${GITHUB_STEP_SUMMARY}"
        ./check_release_assets.py --version "${{ inputs.release }}" --github | tee "${GITHUB_STEP_SUMMARY}"
        echo '```' >> "${GITHUB_STEP_SUMMARY}"
        echo "::notice::Release: $(gh -R cupy/cupy release view '${{ inputs.release }}' --json 'url' --jq '.url')"

  upload:
    needs: check
    environment:
      name: pypi-release
      url: https://pypi.org/org/cupy/
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - name: Download (sdist)
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh -R cupy/cupy release download "${{ inputs.release }}" --dir dist --pattern "cupy-*.tar.gz"
    - name: Download (wheels)
      if: ${{ inputs.branch != 'main' }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh -R cupy/cupy release download "${{ inputs.release }}" --dir dist --pattern "cupy_*.whl"
    - name: Enumerate Files
      run: |
        cd dist
        echo '```' >> "${GITHUB_STEP_SUMMARY}"
        find . -type f -ls | tee "${GITHUB_STEP_SUMMARY}"
        echo '```' >> "${GITHUB_STEP_SUMMARY}"
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: true
        print-hash: true
